baseURL = 'https://adash28.github.io/One_more_harukikage-blog/'
languageCode = 'en-us'
title = 'One More Harukikage Lab'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    displayFullContent = false
    showReadingTime = true
    math = true