baseURL = 'https://adash28.github.io/One_more_harukikage-blog/'
languageCode = 'en-us'
title = 'One More Harukikage Lab'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    displayFullContent = false
    showReadingTime = true
    math = true

relativeURLs = true
canonifyURLs = true

[[menu.main]]
    name = "AIGC "
    url = "/aigc/"
    weight = 10
[[menu.main]]
    name = "深度学习"
    url = "/dl/"
    weight = 20
